### ISSUE TITLE
FEATURE: Pause After Each Payload

### ISSUE THREAD

**Issue by lauritzh** [lauritzh/domscan#19]
In non-headless mode, an interactive mode would be useful. DOMscan could wait after each payload until user manually continues execution of scan.

**Comment by lauritzh** [comment]
Added in https://github.com/lauritzh/domscan/releases/tag/v0.0.2

**Comment by Teicu** [comment]
Hi, 

The scanner functions flawlessly, but is there a command that eliminates the need to press Enter after each payload? Currently, I receive a lot of  "Press ENTER to continue..."  

Thanks



<img width="377" alt="Screenshot 2023-11-03 at 14 52 21" src="https://github.com/lauritzh/domscan/assets/1572822/e1ae2092-b250-4ac2-a359-bd0a4262be86">

**Comment by lauritzh** [comment]
Hi @Teicu!

Thank you very much for your feedback! :)

I suppose you are running `domscan` with the `--interactive` flag, which causes this behaviour:
```console
$ domscan -h
     _                                     
  __| | ___  _ __ ___  ___  ___ __ _ _ __  
 / _` |/ _ \| '_ ` _ \/ __|/ __/ _` | '_ \ 
| (_| | (_) | | | | | \__ \ (_| (_| | | | |
 \__,_|\___/|_| |_| |_|___/\___\__,_|_| |_|
             
 (C) Lauritz Holtmann, 2023
 
Options:
[...]
  -i, --interactive               Pause on each payload and wait for user input
[...]
```

It is intended to allow manual analysis of each payload. If you do not want to use this mode, you can omit the flag from your command :)

I hope this helps! Please let me know in case you have any further comments or questions.


Best regards and have a great day,

Lauritz
