### ISSUE TITLE
Seems stuck in a loop

### ISSUE THREAD

**Issue by ericaliebmann** [lauritzh/domscan#75]
When scanning a url, it keeps outputting the same finding
<img width="415" alt="Screenshot 2023-12-06 at 5 33 44 PM" src="https://github.com/lauritzh/domscan/assets/79177074/31a5edc5-9889-4c52-8aef-2b85675117c5">

**Comment by lauritzh** [comment]
Hi @ericaliebmann,

Thank you very much for reaching out! :)

Could you please check what *really* happens within the browser using the `--headless false` flag? Using this flag, the browser should be launched in regular (non-headless) mode. You could further delay payload testing by using `--interactive false`.


Thanks in advance and best regards,

Lauritz

**Comment by lauritzh** [comment]
Hi @ericaliebmann,

have you found the time to re-check this issue?
If your problem was resolved, I would like to go ahead and close this issue :)


Best regards and have a great day,

Lauritz

**Comment by lauritzh** [comment]
Hi there!
 
I am closing this issue as it seems to be resolved. If you have any comments or questions, please let me know!

Best regards,

Lauritz
